apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l84p8ynyk-java-springboot 
  janus-idp.io/tekton: l84p8ynyk-java-springboot
  backstage.io/kubernetes-id: l84p8ynyk-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l84p8ynyk-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml